### PR TITLE
Enable TravisCI 

### LINKED ISSUE #17: Add continuous integration
Travis CI should be set up for this project to make sure the code builds without errors, adheres to the linter rules and is thoroughly tested (maybe Codecov).
A badge for the build should be added to the README.

### PR DESCRIPTION
**Pull request by oncletom**
For tests and npm publishing.

Secure variables `NPM_EMAIL` and `NPM_TOKEN` would have to be created in TravisCI interface.

- [ ] ~~Code coverage with CodeCov~~ (see #19)
- [x] npm deploy on tag
- [x] tests and linting (thanks to `pretest` script)

closes #17

### CODE REVIEW

**Comment by connium** [comment]
Hello @oncletom, thank you very much for your contribution! This helps me a lot as I am not familiar with Travis CI so far.

I've added this repo to Travis CI and set up the environment variables.

Are the leading dashes in line 8, 11, 14 by intention? I saw them in some example configs while they were not present in others.

**Comment by connium** [comment]
One other question: Do I have to modify any jest or tsc configurations?
See [Codecov TypeScript Example](https://github.com/codecov/example-typescript) and [Codecov NodeJS / Javascript Example](https://github.com/codecov/example-node).

**Comment by oncletom** [comment]
> This helps me a lot as I am not familiar with Travis CI so far.

Glad this helps 🙂 

> Are the leading dashes in line 8, 11, 14 by intention? I saw them in some example configs while they were not present in others.

The leading dash means "it's a list item" in YAML. I used a list notation even for one item, to make it clear you could do more in the future.

> Do I have to modify any jest or tsc configurations?

I followed the Codecov Typescript example you've linked. I have not tested it and I suspect sourcemaps are not enabled, so the coverage won't be effective in Travis.

And I guess [this doc](https://github.com/codecov/example-node#jest) makes it explicit.

I can dig a bit more if you want, or split the PR in 2 so as you can have tests first and coverage in a second pass (which is more unknown to both of us).

**Comment by connium** [comment]
Good point! Yes, please split it up into two separate PR so we can have Travis build in first.

I'll take a look at the Jest configuration as well.

**Pull request merged**
